### ISSUE TITLE
Install plugin on Eclipse 4.X

### ISSUE THREAD

**Issue by cat0rgi0** [jhudson8/hibernate-synchronizer#1]
Hi J , i'm using your plugin on my project to create Dao object from hbm. 
There is some way to migrate this plugin on Eclipse 4.x plugin structure ?

**Comment by jhudson8** [comment]
hello, I haven't touched this plugin in probably 10 years.  I'd suggest using http://hibernate.org/tools/

**Comment by cat0rgi0** [comment]
Ok il will read better the reference about Hibernate tools. Actually i should generate Dao classes from hbm without any access on Db , and your plugin does this job very well :8ball: 
 Thank you very much for support.
